name: CI ImplementntacionDummie
on: [push]

jobs: 

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3
    
    - name: Despliegue con Docker Compose
      run: |
        docker-compose up -d
        docker ps

    - name: Ejecutar pruebas de aceptación con Postman
      uses: matt-ball/newman-action@v1.0.4
      with:
        # Ruta a tu archivo de colección de Postman (por ejemplo, collection.json)
        collection: collection.json
          


        
