name: CI ImplementntacionDummie
on: [push]

jobs: 

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3
    
    - name: Setup Java JDK
      uses: actions/setup-java@v3.12.0
      with:
        java-version: '11'
        distribution: 'zulu'

    - name: Build Gradle
      run: |
        chmod +x gradlew
        ./gradlew -q projects  # Listar proyectos Gradle
        ./gradlew clean build bootBuildImage  # Construir y crear imágenes Docker para todos los proyectos desde el proyecto padre



