name: CI ImplementntacionDummie
on: [push]

jobs: 

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Despliegue con Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d
        docker ps


        

        

        


        
  



