name: CI ImplementntacionDummie
on: [push]

jobs: 

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3
    
    - name: Despliegue con Docker Compose
      run: |
        docker-compose up -d
        docker ps

    - name: Ejecutar pruebas de aceptación con Postman 
      uses: matt-ball/newman-action@v1.0.4
      with:
        # Ejecuta las pruebas de Postman con Newman
        collection: collection.json
        


        
