name: CI ImplementntacionDummie
on: [push]

jobs: 

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3
    
    - name: Setup Java JDK
      uses: actions/setup-java@v3.12.0
      with:
        java-version: '11'
        distribution: 'zulu'

    - name: Build Gradle
      run: |
        chmod +x gradlew
        ./gradlew -q projects  # Listar proyectos Gradle
        ./gradlew clean build bootBuildImage  # Construir y crear imágenes Docker para todos los proyectos desde el proyecto padre

    - name: Analisis SonarCloud
      run: |
        chmod +x gradlew
        ./gradlew sonar -Dsonar.token=${{ secrets.TOKEN_SONARCLOUD }} # Genera el análisis con el token correspondiente

    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Build
      run: |
        docker build --tag rubejorquera/service-a:latest $GITHUB_WORKSPACE/deploy
        docker images



