name: CI ImplementntacionDummie
on: [push]

jobs: 

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3
    
    - name: Despliegue con Docker Compose
      run: |
        docker-compose up -d
        docker ps

    - name: Set IP Address
      run: echo "::set-env name=SERVICE_A_IP::$(hostname -I | awk '{print $1}')"
    
    - name: Run Postman Tests
      uses: anthonyvscode/newman-action@v1
      with:
        collection: collection.json
        reporters: cli
      env:
        SERVICE_A_IP: ${{ env.SERVICE_A_IP }}
      


        
