name: CI ImplementntacionDummie
on: [push]

jobs: 

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3
    
    - name: Setup Java JDK
      uses: actions/setup-java@v3.12.0
      with:
        java-version: '11'
        distribution: 'zulu'

    - name: Build Gradle
      run: |
        chmod +x gradlew
        ./gradlew -q projects  # Listar proyectos Gradle
        ./gradlew clean build bootBuildImage  # Construir y crear imágenes Docker para todos los proyectos desde el proyecto padre

   
    - name: Docker Tag and Push
      run: |
        docker images | grep spring-multi-module
        # Etiquetar y empujar la imagen para service-a
        docker tag rubejorquera/service-a:latest ${{ secrets.DOCKER_USERNAME }}/service-a:latest
        echo "Imagen etiquetada para service-a: ${{ secrets.DOCKER_USERNAME }}/service-a:latest"
        
    
        # Etiquetar y empujar la imagen para service-b
        docker tag rubejorquera/service-b:latest ${{ secrets.DOCKER_USERNAME }}/service-b:latest
        echo "Imagen etiquetada para service-b: ${{ secrets.DOCKER_USERNAME }}/service-b:latest"
      
    
        # Etiquetar y empujar la imagen para service-c
        docker tag rubejorquera/service-c:latest ${{ secrets.DOCKER_USERNAME }}/service-c:latest
        echo "Imagen etiquetada para service-c: ${{ secrets.DOCKER_USERNAME }}/service-c:latest"
  



