name: CI ImplementntacionDummie
on: [push]

jobs: 

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Configurar Docker
      uses: docker://stable
      with:
        docker-version: '20.10.7' # Versión de Docker que desees utilizar
        
    - name: Despliegue con Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d
        docker ps


        

        

        


        
  



