name: CI ImplementntacionDummie
on: [push]

jobs: 

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3
    
    - name: Setup Java JDK
      uses: actions/setup-java@v3.12.0
      with:
        java-version: '11'
        distribution: 'zulu'

    - name: Build Gradle
      run: |
        chmod +x gradlew
        ./gradlew -q projects  # Listar proyectos Gradle
        ./gradlew clean build bootBuildImage  # Construir y crear imágenes Docker para todos los proyectos desde el proyecto padre

   
    - name: Docker Tag and Push
      run: |
        
        # Se Cambian de nombre de usuario a las imagenes
        docker tag narramadan/spring-multi-module-service-service-a:latest rubejorquera/spring-multi-module-service-service-a:latest
        docker tag narramadan/spring-multi-module-service-service-b:latest rubejorquera/spring-multi-module-service-service-b:latest
        docker tag narramadan/spring-multi-module-service-service-c:latest rubejorquera/spring-multi-module-service-service-c:latest
        docker images | grep spring-multi-module

        

        

        


        
  



