name: CI ImplementntacionDummie
on: [push]

jobs: 

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3
    
    - name: Despliegue con Docker Compose
      run: |
        docker-compose up -d
        docker ps

    - name: Ejecutar pruebas de aceptación con Postman (Local Collection)
      id: run-newman
      uses: anthonyvscode/newman-action@v1
      with:
        collection: collection.json  # Ruta a tu archivo collection.json local
        reporters: cli

    - name: Output summary to console
      run: echo ${{ steps.run-newman.outputs.summary }}


        
